- action:
  - alias: ''
    data:
      entity_id: switch.plug1
    service: switch.turn_on
  alias: Family room light on at sunset
  condition: []
  id: '1518368351969'
  trigger:
  - event: sunset
    platform: sun
- action:
  - data:
      entity_id: switch.plug1
    service: switch.turn_off
  alias: Family room light off at midnight
  condition: []
  id: '1518380606641'
  trigger:
  - at: '23:59'
    platform: time
- action:
  - data:
      entity_id: light.hue_white_lamp_2
    service: light.turn_on
  - data:
      entity_id: light.hue_white_lamp_1
    service: light.turn_on
  - data:
      entity_id: media_player.kitchen_speaker
      message: Hey there, Hass turned on the outside lights
    service: tts.google_say
  alias: Garage lights on at sunset + offset
  condition: []
  id: '1518386340245'
  trigger:
  - event: sunset
    offset: 00:15:00
    platform: sun
- action:
  - data:
      entity_id: light.hue_white_lamp_2
    service: light.turn_off
  - data:
      entity_id: light.hue_white_lamp_1
    service: light.turn_off
  alias: Garage lights off at sunrise
  condition: []
  id: '1518386813532'
  trigger:
  - event: sunrise
    platform: sun
- action:
  - data:
      entity_id: media_player.kitchen_speaker
      message: There was motion detected
    service: tts.google_say
  - data:
      message: Motion has been detected
    service: notify.notify_larry
  alias: Motion detected
  condition: []
  id: '1519065133237'
  trigger:
  - entity_id: binary_sensor.entryway_camera_larscam1_motion_detected
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      message: HASS has started
    service: notify.notify_larry
  alias: HASS has started
  condition: []
  id: '1519067307505'
  trigger:
  - event: start
    platform: homeassistant
- action:
  - data:
      message: HASS has shutdown
    service: notify.notify_larry
  alias: HASS has stopped
  condition: []
  id: '1519067351610'
  trigger:
  - event: shutdown
    platform: homeassistant
- action:
  - data:
      message: Home Assistant update is now available.
    service: notify.notify_larry
  alias: HASS update available
  condition: []
  id: '1519961333155'
  trigger:
  - platform: template
    value_template: "{% set latest_version = states.sensor.web_scrape.state %}\n{%\
      \ set latest_value = latest_version.split(\" \")[2] %}\n{% set current_value\
      \ = states.sensor.current_version.state %}\n{% if latest_value == current_value\
      \ %}\n  true\n{% else %}\n  false\n{% endif %}"
- action:
  - data:
      message: 'Pollen will be bad today: {{ states.sensor.allergy_index_today.state
        }} with rating: {{ states.sensor.allergy_index_today.attributes.rating }} '
    service: notify.notify_larry
  alias: Pollen monitor
  condition:
  - above: '7.2'
    condition: numeric_state
    entity_id: sensor.allergy_index_today
  id: '1519968685186'
  trigger:
  - event: sunrise
    platform: sun
- action:
  - data:
      message: "Weather forecast- today: {{ states.sensor.pws_weather_1d.state }}\n\
        \ tomorrow: {{ states.sensor.pws_weather_2d.state }}"
    service: notify.notify_larry
  alias: Weather forecast
  condition: []
  id: '1519971358060'
  trigger:
  - event: sunrise
    platform: sun
- action:
  - data:
      message: Xbox is online
    service: notify.notify_larry
  alias: xbox is on
  condition: []
  id: '1519972532595'
  trigger:
  - entity_id: sensor.lars01pnw
    from: 'off'
    platform: state
    to: 'on'
