homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 47.6051
  longitude: -122.1134
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction: 

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  #ssl_certificate: /ssl/.home-assistant/certificate.pem
  #ssl_key: /ssl/.home-assistant/privkey.pem

  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# Tracked history is kept for 10 days
recorder:
  purge_keep_days: 10

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# SENSORS
# Weather prediction
sensor:
  - platform: yr
  
  - platform: version

  - platform: scrape
    resource: https://home-assistant.io
    name: Release
    select: ".current-version h1"
    value_template: '{{ value.split(":")[1] }}'

# Pollen 
  - platform: pollen
    zip_code: "98074"
    monitored_conditions:
      - allergy_average_forecasted
      #- allergy_average_historical
      - allergy_index_today
      - allergy_index_tomorrow
      - allergy_index_yesterday
      #- disease_average_forecasted

#xbox API
  - platform: xbox_live
    api_key: !secret xbox_apikey 
    xuid: !secret xbox_xuid 
    scan_interval: 60

# wunderground
  - platform: wunderground
    api_key: !secret wu_apikey 
    monitored_conditions:
      - weather_1d
      - weather_2d

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# dropcam/nest
nest:
  client_id: !secret nest_clientid 
  client_secret: !secret nest_secret 
  
#notify pushbullet
notify:
  - name: NOTIFY_LARRY
    platform: pushbullet
    api_key: !secret pushbullet_apikey 

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

